name: Notes

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          secrets: GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
          push: true
          tags: ghcr.io/edi334/DevPlantAssignment:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull & run image on server
        uses: appleboy/ssh-action@master
        with:
          host: gdscupt.tech
          port: 69
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: /home/docker/deploy/deploy.sh /home/docker/edi/notes-app
